[package]
edition = "2021"
name = "bevy_magic_light_2d"
version = "0.3.0"

[lib]
name = "bevy_magic_light_2d"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.68"
bevy = "0.9.1"
bevy_egui = { version = "0.18.0", default-features = false }
bevy-inspector-egui = "0.15.0"
bevy-inspector-egui-derive = "0.15.0"
egui = { version = "0.20.1", features = ["bytemuck"] }
encase = "0.4.1"
log = "0.4.17"
rand = "0.8.5"

[profile.release]
codegen-units = 1
debug = false
lto = "thin"
opt-level = 3
panic = "abort"

[profile.dev.package."*"]
opt-level = 3
debug = true
incremental = true

[profile.dev]
codegen-units = 16
opt-level = 0
debug = true
incremental = true
